name: CI
on:
  push
jobs:

  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@24.3.0
        with:
          version: 24.3.0

  isort:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - name: Run pylint
        run: |
          poetry run isort \
            --check \
            --color \
            --diff \
            ultralight_cffi \
            tests

  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - name: Run mypy
        run: poetry run mypy ultralight_cffi

  pylint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - name: Run pylint
        run: poetry run pylint ultralight_cffi

  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y 7zip
      - name: Download and extract Ultralight SDK
        run: ./scripts/fetch_sdk
      - name: Run pytest
        run: |
          poetry run pytest \
            -p no:only \
            --strict-markers \
            -vv
